package com.rmtz.calendar.libs

class Greetings {
    companion object {
        fun Generate(): String {
            val greetings = listOf(
                "guten Tag",
                "good evening",
                "what's the rumpus?",
                "how's it going?",
                "what's the dilly?",
                "sup",
                "hola",
                "how's it hanging?",
                "how ya goin?",
                "what's happening?",
                "What's in the bag?",
                "wussup?",
                "what's cooking?",
                "yello",
                "what's shaking?",
                "what ho?",
                "holla",
                "'sup?",
                "whazzup?",
                "ahoy",
                "howzit?",
                "what up?",
                "konnichi wa",
                "what's poppin'?",
                "what's up?",
                "'sup, b?",
                "how goes it?",
                "what's new?",
                "what's crack-a-lackin'?",
                "what's the haps?",
                "good day",
                "good night",
                "what's the dizzle?",
                "hey",
                "what's crackin'?",
                "aloha",
                "what's cracking?",
                "how do?",
                "good morning",
                "howsyamomanem?",
                "good afternoon",
                "salutations",
                "how's it hanging?",
                "hello",
                "wassap?",
                "yo"
            )
            return greetings.random()
        }

        fun Quote(): String {
            val topics = listOf(
                "Neon swords dance in the cool blue abyss",
                "Where a cyberpunk samurai finds his silent bliss",
                "Water whispers secrets of the city's core",
                "In the cavern's heart, he's the ultimate boss",
                "The glow of fish a digital ballet",
                "Guarding treasures of a submerged metropolis play",
                "Summer's warmth forgotten in this deep dive",
                "He lives by the code of the cybernetic jive",
                "Tech and tradition intertwine so neat",
                "As he seeks peace in the aquatic street",
                "A silent guardian in the ocean's keep",
                "This samurai's spirit never retreats",
                "In the shadow of ruins, he finds his light",
                "Guiding him through the water's eternal night",
                "In the pulse of circuits, he finds his might",
                "The cyberpunk samurai, a beacon so bright",
                "A mech minion gleams amidst the snow",
                "Its gears and joints whisper tales of yore",
                "With each step taken in the frosty glow",
                "It guards the village from the night's cold roar",
                "In moonlit nights, it stands so tall and proud",
                "A beacon of hope, a sentinel endowed",
                "The winter chill does not make it slow",
                "For warmth and peace, it ceaselessly allowed",
                "In a village basked in summer's cheer",
                "A mech minion toils, year after year",
                "With gears that whir and a metallic hum",
                "It tends the fields 'neath the fiery sun",
                "In every seed, in every sprout",
                "Its mechanical heart holds no doubt",
                "It serves the land with a gentle might",
                "A silent sentinel through the warm day's light",
                "In peaks where the sun kisses the earth",
                "Roams a demon, with sword and soul of fiery birth",
                "Through the lush green, a shadow of might",
                "Guarding the tranquil, with fierce demonic plight",
                "He slices the air, swift as a summer breeze",
                "Silent guardian 'neath the willow trees",
                "The demon samurai, with a heart so cold",
                "Walks his solitary path, with a fiery mold",
                "A glowing sprite amidst the frost and rime",
                "In neon hues, it whispers through the night sublime",
                "With circuits pulsing, heart of silicon and light",
                "It brings to village life a futuristic sight",
                "The minion moves with grace through winter's chill",
                "Its digital essence, the villagers' thrill",
                "In a world of steel and code, it finds its place",
                "A beacon of warmth in the cold embrace"
            )
            return topics.random()
        }
    }
}